name: E2E Test
on:
  push:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Install supported browsers
        run: npx playwright install
      - name: Capture production screenshots
        run: npm run cap:pro
      - name: Start app and test
        run: |
          npm run start &
          npm run test
